/*****************************************************************************
* FileName     : Port_core.c
* Author       : &{user}
* Created      : Jan 16, 2022
* Description  :
*
*
*****************************************************************************/

#include "Port_core.h"
#include "STM32F303RET6.h"

#if( PORT_CFG_PORT_PIN_LOCK_API_ENABLE  == STD_ON )
	void Port_PinLock(uint8_t Port, uint8_t Pin){

	}
#endif /* End of #if( PORT_CFG_PORT_PIN_LOCK_API_ENABLE  == STD_ON ) */

#if( PORT_CFG_PORT_PIN_UNLOCK_API_ENABLE  == STD_ON )
	void Port_PinUnlock(uint8_t Port, uint8_t Pin){

	}
#endif /* End of #if( PORT_CFG_PORT_PIN_UNLOCK_API_ENABLE  == STD_ON ) */

#if( PORT_CFG_PORT_LOCK_API_ENABLE  == STD_ON )
	void Port_PortLock(uint8_t Port){

	}
#endif /* End of #if( PORT_CFG_PORT_LOCK_API_ENABLE  == STD_ON ) */

#if( PORT_CFG_PORT_UNLOCK_API_ENABLE  == STD_ON )
	void Port_PortUnlock(uint8_t Port){

	}
#endif /* End of #if( PORT_CFG_PORT_UNLOCK_API_ENABLE  == STD_ON ) */


void PORT_Init(){
		#if(PORT_CFG_PORT_A_ENABLE == STD_ON)
		/* Enable PORT A Clock */
		RCC_REG_AHBENR |= (1<<17);

		/* Configure Port Mode for PORT A */
		PORT_REG_PORT_A_MODER = PORT_CONST_PORT_A_MOD_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_A_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT A */
		PORT_REG_PORT_A_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_A_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT A */
		PORT_REG_PORT_A_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_A_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT A */
		PORT_REG_PORT_A_PUPDR = PORT_REG_PUPDR_PORT_A_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_A_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_A_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT A */
		PORT_REG_PORT_A_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_A_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT A */
		PORT_REG_PORT_A_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_A_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_A_ENABLE == STD_ON) */

		#if(PORT_CFG_PORT_B_ENABLE == STD_ON)
		/* Configure Port Mode for PORT_B */
		PORT_REG_PORT_B_MODER = PORT_CONST_PORT_B_MOD_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_B_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT_B */
		PORT_REG_PORT_B_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_B_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT_B */
		PORT_REG_PORT_B_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_B_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT_B */
		PORT_REG_PORT_B_PUPDR = PORT_REG_PUPDR_PORT_B_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_B_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_B_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT_B */
		PORT_REG_PORT_B_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_B_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT_B */
		PORT_REG_PORT_B_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_B_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_B_ENABLE == STD_ON) */


		#if(PORT_CFG_PORT_C_ENABLE == STD_ON)
		/* Configure Port Mode for PORT_C */
		PORT_REG_PORT_C_MODER = PORT_CONST_PORT_C_MOD_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_C_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT_C */
		PORT_REG_PORT_C_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_C_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT_C */
		PORT_REG_PORT_C_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_C_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT_C */
		PORT_REG_PORT_C_PUPDR = PORT_REG_PUPDR_PORT_C_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_C_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_C_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT_C */
		PORT_REG_PORT_C_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_C_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT_C */
		PORT_REG_PORT_C_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_C_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_C_ENABLE == STD_ON) */


		#if(PORT_CFG_PORT_D_ENABLE == STD_ON)
		/* Configure Port Mode for PORT_D */
		PORT_REG_PORT_D_MODER = PORT_REG_MODER_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_D_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT_D */
		PORT_REG_PORT_D_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_D_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT_D */
		PORT_REG_PORT_D_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_D_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT_D */
		PORT_REG_PORT_D_PUPDR = PORT_REG_PUPDR_PORT_D_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_D_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_D_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT_D */
		PORT_REG_PORT_D_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_D_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT_D */
		PORT_REG_PORT_D_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_D_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_D_ENABLE == STD_ON) */

		#if(PORT_CFG_PORT_E_ENABLE == STD_ON)
		/* Configure Port Mode for PORT_E */
		PORT_REG_PORT_E_MODER = PORT_REG_MODER_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_E_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT_E */
		PORT_REG_PORT_E_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_E_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT_E */
		PORT_REG_PORT_E_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_E_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT_E */
		PORT_REG_PORT_E_PUPDR = PORT_REG_PUPDR_PORT_E_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_E_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_E_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT_E */
		PORT_REG_PORT_E_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_E_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT_E */
		PORT_REG_PORT_E_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_E_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_E_ENABLE == STD_ON) */


		#if(PORT_CFG_PORT_F_ENABLE == STD_ON)
		/* Configure Port Mode for PORT_F */
		PORT_REG_PORT_F_MODER = PORT_REG_MODER_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_F_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT_F */
		PORT_REG_PORT_F_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_F_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT_F */
		PORT_REG_PORT_F_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_F_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT_F */
		PORT_REG_PORT_F_PUPDR = PORT_REG_PUPDR_PORT_F_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_F_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_F_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT_F */
		PORT_REG_PORT_F_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_F_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT_F */
		PORT_REG_PORT_F_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_F_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_F_ENABLE == STD_ON) */

		#if(PORT_CFG_PORT_G_ENABLE == STD_ON)
		/* Configure Port Mode for PORT_G */
		PORT_REG_PORT_G_MODER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_G_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT_G */
		PORT_REG_PORT_G_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_G_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT_G */
		PORT_REG_PORT_G_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_G_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT_G */
		PORT_REG_PORT_G_PUPDR = PORT_REG_PUPDR_PORT_G_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_G_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_G_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT_G */
		PORT_REG_PORT_G_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_G_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT_G */
		PORT_REG_PORT_G_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_G_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_G_ENABLE == STD_ON) */

		#if(PORT_CFG_PORT_H_ENABLE == STD_ON)
		/* Configure Port Mode for PORT_H */
		PORT_REG_PORT_H_MODER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_0_MODE) << PORT_REG_MODER_MODER0_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_1_MODE) << PORT_REG_MODER_MODER1_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_2_MODE) << PORT_REG_MODER_MODER2_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_3_MODE) << PORT_REG_MODER_MODER3_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_4_MODE) << PORT_REG_MODER_MODER4_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_5_MODE) << PORT_REG_MODER_MODER5_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_6_MODE) << PORT_REG_MODER_MODER6_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_7_MODE) << PORT_REG_MODER_MODER7_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_8_MODE) << PORT_REG_MODER_MODER8_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_9_MODE) << PORT_REG_MODER_MODER9_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_10_MODE) << PORT_REG_MODER_MODER10_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_11_MODE) << PORT_REG_MODER_MODER11_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_12_MODE) << PORT_REG_MODER_MODER12_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_13_MODE) << PORT_REG_MODER_MODER13_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_14_MODE) << PORT_REG_MODER_MODER14_0)
											| ( (PORT_REG_MODER_BITS_MASK & PORT_CFG_PORT_H_PIN_15_MODE) << PORT_REG_MODER_MODER15_0);

		/* Configure Port Output Type for PORT_H */
		PORT_REG_PORT_H_OTYPER = PORT_REG_OTYPER_RESET_VALUE | ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_0_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER0_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_1_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER1_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_2_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER2_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_3_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER3_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_4_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER4_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_5_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER5_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_6_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER6_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_7_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER7_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_8_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER8_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_9_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER9_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_10_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER10_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_11_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER11_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_12_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER12_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_13_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER13_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_14_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER14_0)
											| ( (PORT_REG_OTYPER_BITS_MASK & PORT_CFG_PORT_H_PIN_15_OUTPUT_TYPE) << PORT_REG_OTYPER_OTYPER15_0);

		/* Configure Port Output Speed for PORT_H */
		PORT_REG_PORT_H_OSPEEDR = PORT_REG_OSPEEDR_RESET_VALUE | ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_0_SPEED) << PORT_REG_OSPEEDR_OSPEEDR0_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_1_SPEED) << PORT_REG_OSPEEDR_OSPEEDR1_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_2_SPEED) << PORT_REG_OSPEEDR_OSPEEDR2_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_3_SPEED) << PORT_REG_OSPEEDR_OSPEEDR3_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_4_SPEED) << PORT_REG_OSPEEDR_OSPEEDR4_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_5_SPEED) << PORT_REG_OSPEEDR_OSPEEDR5_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_6_SPEED) << PORT_REG_OSPEEDR_OSPEEDR6_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_7_SPEED) << PORT_REG_OSPEEDR_OSPEEDR7_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_8_SPEED) << PORT_REG_OSPEEDR_OSPEEDR8_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_9_SPEED) << PORT_REG_OSPEEDR_OSPEEDR9_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_10_SPEED) << PORT_REG_OSPEEDR_OSPEEDR10_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_11_SPEED) << PORT_REG_OSPEEDR_OSPEEDR11_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_12_SPEED) << PORT_REG_OSPEEDR_OSPEEDR12_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_13_SPEED) << PORT_REG_OSPEEDR_OSPEEDR13_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_14_SPEED) << PORT_REG_OSPEEDR_OSPEEDR14_0)
											| ( (PORT_REG_OSPEEDR_BITS_MASK & PORT_CFG_PORT_H_PIN_15_SPEED) << PORT_REG_OSPEEDR_OSPEEDR15_0);

		/* Configure Port Output Speed for PORT_H */
		PORT_REG_PORT_H_PUPDR = PORT_REG_PUPDR_PORT_H_RESET_VALUE | ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_0_PULL_TYPE) << PORT_REG_PUPDR_PUPDR0_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_1_PULL_TYPE) << PORT_REG_PUPDR_PUPDR1_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_2_PULL_TYPE) << PORT_REG_PUPDR_PUPDR2_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_3_PULL_TYPE) << PORT_REG_PUPDR_PUPDR3_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_4_PULL_TYPE) << PORT_REG_PUPDR_PUPDR4_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_5_PULL_TYPE) << PORT_REG_PUPDR_PUPDR5_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_6_PULL_TYPE) << PORT_REG_PUPDR_PUPDR6_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_7_PULL_TYPE) << PORT_REG_PUPDR_PUPDR7_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_8_PULL_TYPE) << PORT_REG_PUPDR_PUPDR8_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_9_PULL_TYPE) << PORT_REG_PUPDR_PUPDR9_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_10_PULL_TYPE) << PORT_REG_PUPDR_PUPDR10_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_11_PULL_TYPE) << PORT_REG_PUPDR_PUPDR11_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_12_PULL_TYPE) << PORT_REG_PUPDR_PUPDR12_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_13_PULL_TYPE) << PORT_REG_PUPDR_PUPDR13_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_14_PULL_TYPE) << PORT_REG_PUPDR_PUPDR14_0)
											| ( (PORT_REG_PUPDR_BITS_MASK & PORT_CFG_PORT_H_PIN_15_PULL_TYPE) << PORT_REG_PUPDR_PUPDR15_0);

		PORT_REG_PORT_H_LCKR = PORT_REG_LCKR_RESET_VALUE;

		/* Configure Port Output Speed for PORT_H */
		PORT_REG_PORT_H_AFRL = PORT_REG_AFRL_RESET_VALUE | ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_0_ALT_FUNC) << PORT_REG_AFRL_AFRL0_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_1_ALT_FUNC) << PORT_REG_AFRL_AFRL1_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_2_ALT_FUNC) << PORT_REG_AFRL_AFRL2_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_3_ALT_FUNC) << PORT_REG_AFRL_AFRL3_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_4_ALT_FUNC) << PORT_REG_AFRL_AFRL4_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_5_ALT_FUNC) << PORT_REG_AFRL_AFRL5_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_6_ALT_FUNC) << PORT_REG_AFRL_AFRL6_0)
											| ( (PORT_REG_AFRL_BITS_MASK & PORT_CFG_PORT_H_PIN_7_ALT_FUNC) << PORT_REG_AFRL_AFRL7_0);

		/* Configure Port Output Speed for PORT_H */
		PORT_REG_PORT_H_AFRH = PORT_REG_AFRH_RESET_VALUE | ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_0_ALT_FUNC) << PORT_REG_AFRH_AFRH0_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_1_ALT_FUNC) << PORT_REG_AFRH_AFRH1_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_2_ALT_FUNC) << PORT_REG_AFRH_AFRH2_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_3_ALT_FUNC) << PORT_REG_AFRH_AFRH3_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_4_ALT_FUNC) << PORT_REG_AFRH_AFRH4_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_5_ALT_FUNC) << PORT_REG_AFRH_AFRH5_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_6_ALT_FUNC) << PORT_REG_AFRH_AFRH6_0)
											| ( (PORT_REG_AFRH_BITS_MASK & PORT_CFG_PORT_H_PIN_7_ALT_FUNC) << PORT_REG_AFRH_AFRH7_0);


		#endif /* End of #if(PORT_CFG_PORT_H_ENABLE == STD_ON) */


}
